version: '3.7'

services:
  backend:
    container_name: django_rest
    build:
      context: .
      dockerfile: ./docker/project/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn Movies.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
#    expose:
#      - 8000
    volumes:
      - ./Movies:/usr/src/app
    depends_on:
      - db

#  nginx:
#    build:
#      context: .
#      dockerfile: ./docker/nginx/Dockerfile
#    ports:
#      - 8000:80
#    volumes:
#      - ./Movies:/home/app/web
#    depends_on:
#      - backend

  db:
    image: postgres:15
    container_name: postgres
    volumes:
#      - ./docker/postgres/db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=db_postgres
      - POSTGRES_POST=5432
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=000000
      - POSTGRES_DB=mydb
      - PGDATA=/tmp

  pgadmin:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=123123
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    volumes:
      - ./docker/postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata: